ifndef INCLUDED_AUTOCONF_MK
INCLUDED_AUTOCONF_MK = autoconf.mk
include $(DEPTH)/config/emptyvars.mk
ACCESSIBILITY = 1
ACDEFINES = -DACCESSIBILITY=1 -DATK_MAJOR_VERSION='' -DATK_MINOR_VERSION='' -DATK_REV_VERSION='' -DBROWSER_CHROME_URL=chrome://browser/content/browser.xhtml -DBROWSER_CHROME_URL_QUOTED='"chrome://browser/content/browser.xhtml"' -DBUILD_CTYPES=1 -DCROSS_COMPILE='' -DENABLE_SHARED_MEMORY=1 -DENABLE_SYSTEM_EXTENSION_DIRS=1 -DENABLE_TESTS=1 -DENABLE_WASM_BULKMEM_OPS=1 -DENABLE_WASM_MULTI_VALUE=1 -DENABLE_WASM_REFTYPES=1 -DFORCE_PR_LOG=1 -DGL_PROVIDER_EGL=1 -DGTEST_HAS_RTTI=0 -DHAVE_64BIT_BUILD=1 -DHAVE_FORCEINLINE=1 -DHAVE_LOCALECONV=1 -DJS_64BIT=1 -DJS_CODEGEN_X64=1 -DJS_DEFAULT_JITREPORT_GRANULARITY=3 -DJS_HAS_INTL_API=1 -DJS_PUNBOX64=1 -DMALLOC_H='<malloc.h>' -DMOZILLA_UAVERSION='"80.0"' -DMOZILLA_VERSION='"80.0"' -DMOZILLA_VERSION_U=80.0 -DMOZ_ACCESSIBILITY_ATK=1 -DMOZ_APP_UA_NAME='""' -DMOZ_APP_UA_VERSION='"80.0"' -DMOZ_AV1=1 -DMOZ_BLOCK_PROFILE_DOWNGRADE=1 -DMOZ_BUILD_APP=browser -DMOZ_BUNDLED_FONTS=1 -DMOZ_CRASHREPORTER=1 -DMOZ_DATA_REPORTING=1 -DMOZ_DEDICATED_PROFILES=1 -DMOZ_DISTRIBUTION_ID='"org.mozilla"' -DMOZ_DLL_PREFIX='"lib"' -DMOZ_DLL_SUFFIX='".so"' -DMOZ_ENABLE_DBUS=1 -DMOZ_ENABLE_FORKSERVER=1 -DMOZ_ENABLE_SKIA=1 -DMOZ_FFMPEG=1 -DMOZ_FFVPX=1 -DMOZ_FFVPX_AUDIOONLY=1 -DMOZ_FMP4=1 -DMOZ_GECKO_PROFILER=1 -DMOZ_GECKO_PROFILER_PARSE_ELF=1 -DMOZ_GLUE_IN_PROGRAM=1 -DMOZ_HAS_REMOTE=1 -DMOZ_INSTRUMENT_EVENT_LOOP=1 -DMOZ_LOGGING=1 -DMOZ_MACBUNDLE_ID=org.mozilla.dotbrowser -DMOZ_NEW_CERT_STORAGE=1 -DMOZ_NORMANDY=1 -DMOZ_PEERCONNECTION=1 -DMOZ_PLACES=1 -DMOZ_PROFILER_MEMORY=1 -DMOZ_RAW=1 -DMOZ_SAMPLE_TYPE_FLOAT32=1 -DMOZ_SANDBOX=1 -DMOZ_SCTP=1 -DMOZ_SERVICES_HEALTHREPORT=1 -DMOZ_SRTP=1 -DMOZ_STATIC_JS=1 -DMOZ_TREE_CAIRO=1 -DMOZ_TREE_PIXMAN=1 -DMOZ_UPDATER=1 -DMOZ_UPDATE_CHANNEL=default -DMOZ_USER_DIR='".mozilla"' -DMOZ_VERIFY_MAR_SIGNATURE=1 -DMOZ_VORBIS=1 -DMOZ_WAYLAND=1 -DMOZ_WEBM_ENCODER=1 -DMOZ_WEBRTC=1 -DMOZ_WEBRTC_ASSERT_ALWAYS=1 -DMOZ_WEBRTC_SIGNALING=1 -DMOZ_WEBSPEECH=1 -DMOZ_WEBSPEECH_TEST_BACKEND=1 -DMOZ_WIDGET_GTK=1 -DMOZ_X11=1 -DMOZ_XUL=1 -DNO_NSPR_10_SUPPORT=1 -DNS_PRINTING=1 -DNS_PRINT_PREVIEW=1 -DRELEASE_OR_BETA=1 -DSTATIC_JS_API=1 -DUSE_SKIA=1 -DU_STATIC_IMPLEMENTATION=1 -DU_USING_ICU_NAMESPACE=0 -DXP_LINUX=1 -DXP_UNIX=1
ANDROID_PACKAGE_NAME = org.mozilla.firefox
AUTOCONF = /usr/bin/autoconf-2.13
AWK = /usr/bin/gawk
BINDGEN_SYSTEM_FLAGS =   -I/home/kieran/Documents/browser/obj-x86_64-pc-linux-gnu/dist/include/nss  -I/home/kieran/Documents/browser/obj-x86_64-pc-linux-gnu/dist/include/cairo
BINDGEN_SYSTEM_TOML_FLAGS = '-I/home/kieran/Documents/browser/obj-x86_64-pc-linux-gnu/dist/include/nss', '-I/home/kieran/Documents/browser/obj-x86_64-pc-linux-gnu/dist/include/cairo'
BUILD_BACKENDS = FasterMake+RecursiveMake
BUILD_CTYPES = 1
CPU_ARCH = x86_64
CROSS_LIB = /usr/x86_64-pc-linux-gnu
DIST = /home/kieran/Documents/browser/obj-x86_64-pc-linux-gnu/dist
DLL_PREFIX = lib
DLL_SUFFIX = .so
ENABLE_MARIONETTE = 1
ENABLE_SHARED_MEMORY = 1
ENABLE_TESTS = 1
ENABLE_WASM_BULKMEM_OPS = 1
ENABLE_WASM_MULTI_VALUE = 1
ENABLE_WASM_REFTYPES = 1
FC_FONT_FEATURE = #define CAIRO_HAS_FC_FONT 1
GIT = /usr/bin/git
GMAKE = /usr/bin/make
GRE_MILESTONE = 80.0
HAVE_64BIT_BUILD = 1
HOST_CFLAGS = -DXP_UNIX
HOST_CMFLAGS = -x objective-c -fobjc-exceptions
HOST_CMMFLAGS = -x objective-c++ -fobjc-exceptions
HOST_CPU_ARCH = x86_64
HOST_DLL_PREFIX = lib
HOST_DLL_SUFFIX = .so
HOST_OPTIMIZE_FLAGS = -O3
HOST_OS_ARCH = Linux
INTEL_ARCHITECTURE = 1
IPDL_ROOT = /home/kieran/Documents/browser/obj-x86_64-pc-linux-gnu/ipc/ipdl
JS_CODEGEN_X64 = 1
JS_DISABLE_SHELL = 1
JS_HAS_INTL_API = 1
L10NBASEDIR = /home/kieran/.mozbuild/l10n-central
LIB_PREFIX = lib
LIB_SUFFIX = a
MAKENSISU_FLAGS = -nocd
MOZCONFIG = /home/kieran/Documents/browser/mozconfig
MOZILLA_SYMBOLVERSION = 80
MOZILLA_VERSION = 80.0
MOZ_ADJUST_SDK_KEY = no-adjust-sdk-key
MOZ_APP_BASENAME = Firefox
MOZ_APP_DISPLAYNAME = Dot Browser
MOZ_APP_ID = {ec8030f7-c20a-464f-9b0e-13a3a9e97384}
MOZ_APP_MAXVERSION = 80.*
MOZ_APP_NAME = firefox
MOZ_APP_REMOTINGNAME = firefox
MOZ_APP_VENDOR = Mozilla
MOZ_APP_VERSION = 80.0
MOZ_APP_VERSION_DISPLAY = 80.0
MOZ_ARTIFACT_BUILDS = 1
MOZ_AUTH_EXTENSION = 1
MOZ_AV1 = 1
MOZ_BING_API_CLIENTID = no-bing-api-clientid
MOZ_BING_API_KEY = no-bing-api-key
MOZ_BLOCK_PROFILE_DOWNGRADE = 1
MOZ_BRANDING_DIRECTORY = browser/branding/dot
MOZ_BUILD_APP = browser
MOZ_BUILD_ROOT = /home/kieran/Documents/browser/obj-x86_64-pc-linux-gnu
MOZ_CAIRO_CFLAGS = -I/home/kieran/Documents/browser/obj-x86_64-pc-linux-gnu/dist/include/cairo
MOZ_CAIRO_OSLIBS = -lXrender
MOZ_CHILD_PROCESS_BUNDLE = plugin-container.app/Contents/MacOS/
MOZ_CHILD_PROCESS_BUNDLENAME = Dot BrowserCP
MOZ_CHILD_PROCESS_NAME = plugin-container
MOZ_CONFIGURE_OPTIONS = --enable-artifact-builds MAKE=/usr/bin/make
MOZ_CRASHREPORTER = 1
MOZ_DATA_REPORTING = 1
MOZ_DEBUG_DEFINES = NDEBUG TRIMMED
MOZ_DEDICATED_PROFILES = 1
MOZ_DEVTOOLS = all
MOZ_DISTRIBUTION_ID = org.mozilla
MOZ_EME_MODULES = widevine
MOZ_ENABLE_DBUS = 1
MOZ_ENABLE_FORKSERVER = 1
MOZ_ENABLE_SKIA = 1
MOZ_FFMPEG = 1
MOZ_FFVPX = 1
MOZ_FFVPX_AUDIOONLY = 1
MOZ_FIX_LINK_PATHS = -Wl,-rpath-link,/home/kieran/Documents/browser/obj-x86_64-pc-linux-gnu/dist/bin -Wl,-rpath-link,/usr/local/lib
MOZ_FMP4 = 1
MOZ_FS_LAYOUT = unix
MOZ_GECKO_PROFILER = 1
MOZ_GECKO_PROFILER_PARSE_ELF = 1
MOZ_GLUE_IN_PROGRAM = 1
MOZ_GL_DEFAULT_PROVIDER = EGL
MOZ_GOOGLE_LOCATION_SERVICE_API_KEY = no-google-location-service-api-key
MOZ_GOOGLE_SAFEBROWSING_API_KEY = no-google-safebrowsing-api-key
MOZ_HAS_REMOTE = 1
MOZ_ICU_VERSION = 67
MOZ_INSTRUMENT_EVENT_LOOP = 1
MOZ_JAR_MAKER_FILE_FORMAT = symlink
MOZ_LEANPLUM_SDK_CLIENTID = no-leanplum-sdk-clientid
MOZ_LEANPLUM_SDK_KEY = no-leanplum-sdk-key
MOZ_MACBUNDLE_ID = org.mozilla.dotbrowser
MOZ_MACBUNDLE_NAME = Dot Browser.app
MOZ_MOZILLA_API_KEY = no-mozilla-api-key
MOZ_NEW_CERT_STORAGE = 1
MOZ_NORMANDY = 1
MOZ_NO_DEBUG_RTL = 1
MOZ_OPTIMIZE_FLAGS = -O
MOZ_PACKAGER_FORMAT = omni
MOZ_PDF_PRINTING = 1
MOZ_PEERCONNECTION = 1
MOZ_PLACES = 1
MOZ_POCKET_API_KEY = no-pocket-api-key
MOZ_PREF_EXTENSIONS = 1
MOZ_PROFILER_MEMORY = 1
MOZ_PROFILE_MIGRATOR = 1
MOZ_RAW = 1
MOZ_SAMPLE_TYPE_FLOAT32 = 1
MOZ_SANDBOX = 1
MOZ_SCTP = 1
MOZ_SERVICES_HEALTHREPORT = 1
MOZ_SERVICES_SYNC = 1
MOZ_SPELLCHECK = 1
MOZ_SRTP = 1
MOZ_SYNTH_SPEECHD = 1
MOZ_TREE_CAIRO = 1
MOZ_TREE_PIXMAN = 1
MOZ_UI_LOCALE = en-US
MOZ_UNIVERSALCHARDET = 1
MOZ_UPDATER = 1
MOZ_UPDATE_CHANNEL = default
MOZ_VERIFY_MAR_SIGNATURE = 1
MOZ_VORBIS = 1
MOZ_WAYLAND = 1
MOZ_WEBM_ENCODER = 1
MOZ_WEBRTC = 1
MOZ_WEBRTC_ASSERT_ALWAYS = 1
MOZ_WEBRTC_HAVE_ETHTOOL_SPEED_HI = 1
MOZ_WEBRTC_SIGNALING = 1
MOZ_WEBRTC_X11_LIBS = -lXext -lXdamage -lXfixes -lXcomposite
MOZ_WEBSPEECH = 1
MOZ_WEBSPEECH_TEST_BACKEND = 1
MOZ_WIDGET_TOOLKIT = gtk
MOZ_X11 = 1
MOZ_XUL = 1
MOZ_ZIPWRITER = 1
NECKO_WIFI = 1
NECKO_WIFI_DBUS = 1
NODEJS = /home/kieran/.mozbuild/node/bin/node
NSS_CFLAGS = -I/home/kieran/Documents/browser/obj-x86_64-pc-linux-gnu/dist/include/nss
NS_PRINTING = 1
OBJCOPY = /usr/bin/objcopy
OBJ_SUFFIX = o
OMNIJAR_NAME = omni.ja
OS_ARCH = Linux
OS_COMPILE_CMFLAGS = -x objective-c -fobjc-exceptions
OS_COMPILE_CMMFLAGS = -x objective-c++ -fobjc-exceptions
OS_TARGET = Linux
PDF_SURFACE_FEATURE = #define CAIRO_HAS_PDF_SURFACE 1
PERL = /usr/bin/perl
PKG_SKIP_STRIP = 1
PS_SURFACE_FEATURE = #define CAIRO_HAS_PS_SURFACE 1
PYTHON3 = /home/kieran/Documents/browser/obj-x86_64-pc-linux-gnu/_virtualenvs/init_py3/bin/python
PYTHON3_VERSION = 3.8.5
RELEASE_OR_BETA = 1
RUST_LIB_PREFIX = lib
RUST_LIB_SUFFIX = a
SHELL = /bin/sh
SKIA_INCLUDES = /gfx/skia /gfx/skia/skia
TAR = /usr/bin/tar
TARGET_CPU = x86_64
TARGET_ENDIANNESS = little
TARGET_OS = linux-gnu
TEE_SURFACE_FEATURE = #define CAIRO_HAS_TEE_SURFACE 1
UNZIP = /usr/bin/unzip
VCS_CHECKOUT_TYPE = git
WASM_OBJ_SUFFIX = wasm
WEBIDL_ROOT = /home/kieran/Documents/browser/obj-x86_64-pc-linux-gnu/dom/bindings
XARGS = /usr/bin/xargs
XLIB_SURFACE_FEATURE = #define CAIRO_HAS_XLIB_SURFACE 1
XLIB_XRENDER_SURFACE_FEATURE = #define CAIRO_HAS_XLIB_XRENDER_SURFACE 1
XPCOM_ROOT = /home/kieran/Documents/browser/obj-x86_64-pc-linux-gnu/xpcom/components
ZIP = /usr/bin/zip
bindir = ${exec_prefix}/bin
build = x86_64-pc-linux-gnu
build_alias = x86_64-pc-linux-gnu
build_cpu = x86_64
build_os = linux-gnu
build_vendor = pc
datadir = ${prefix}/share
exec_prefix = ${prefix}
host = x86_64-pc-linux-gnu
host_alias = x86_64-pc-linux-gnu
host_cpu = x86_64
host_os = linux-gnu
host_vendor = pc
includedir = ${prefix}/include
infodir = ${prefix}/info
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localstatedir = ${prefix}/var
mandir = ${prefix}/man
oldincludedir = /usr/include
prefix = /usr/local
program_transform_name = s,x,x,
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
sysconfdir = ${prefix}/etc
target = x86_64-pc-linux-gnu
target_alias = x86_64-pc-linux-gnu
target_cpu = x86_64
target_os = linux-gnu
target_vendor = pc
top_srcdir = /home/kieran/Documents/browser
include $(topsrcdir)/config/baseconfig.mk
endif
