# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

DEFINES += -DNDEBUG=1 -DTRIMMED=1 -DOS_POSIX=1 -DOS_LINUX=1 -DOS_ARCH=Linux -DMOZ_WIDGET_TOOLKIT=gtk -DMOZ_SERVICES_SYNC -DMOZ_BUILD_APP_IS_BROWSER
DIRS := test/gtest
include $(topsrcdir)/config/AB_rCD.mk
init/StaticPrefListAll.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefListAll.h
StaticPrefsAll.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefsAll.h
init/StaticPrefList_accessibility.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_accessibility.h
init/StaticPrefList_alerts.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_alerts.h
init/StaticPrefList_apz.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_apz.h
init/StaticPrefList_beacon.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_beacon.h
init/StaticPrefList_bidi.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_bidi.h
init/StaticPrefList_browser.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_browser.h
init/StaticPrefList_canvas.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_canvas.h
init/StaticPrefList_channelclassifier.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_channelclassifier.h
init/StaticPrefList_clipboard.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_clipboard.h
init/StaticPrefList_content.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_content.h
init/StaticPrefList_converter.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_converter.h
init/StaticPrefList_datareporting.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_datareporting.h
init/StaticPrefList_device.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_device.h
init/StaticPrefList_devtools.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_devtools.h
init/StaticPrefList_docshell.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_docshell.h
init/StaticPrefList_dom.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_dom.h
init/StaticPrefList_editor.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_editor.h
init/StaticPrefList_extensions.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_extensions.h
init/StaticPrefList_findbar.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_findbar.h
init/StaticPrefList_fission.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_fission.h
init/StaticPrefList_font.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_font.h
init/StaticPrefList_full_screen_api.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_full_screen_api.h
init/StaticPrefList_general.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_general.h
init/StaticPrefList_geo.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_geo.h
init/StaticPrefList_gfx.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_gfx.h
init/StaticPrefList_gl.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_gl.h
init/StaticPrefList_html5.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_html5.h
init/StaticPrefList_idle_period.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_idle_period.h
init/StaticPrefList_image.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_image.h
init/StaticPrefList_intl.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_intl.h
init/StaticPrefList_javascript.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_javascript.h
init/StaticPrefList_layers.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_layers.h
init/StaticPrefList_layout.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_layout.h
init/StaticPrefList_mathml.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_mathml.h
init/StaticPrefList_media.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_media.h
init/StaticPrefList_mousewheel.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_mousewheel.h
init/StaticPrefList_network.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_network.h
init/StaticPrefList_nglayout.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_nglayout.h
init/StaticPrefList_page_load.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_page_load.h
init/StaticPrefList_permissions.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_permissions.h
init/StaticPrefList_plain_text.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_plain_text.h
init/StaticPrefList_plugin.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_plugin.h
init/StaticPrefList_plugins.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_plugins.h
init/StaticPrefList_preferences.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_preferences.h
init/StaticPrefList_print.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_print.h
init/StaticPrefList_privacy.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_privacy.h
init/StaticPrefList_prompts.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_prompts.h
init/StaticPrefList_security.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_security.h
init/StaticPrefList_slider.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_slider.h
init/StaticPrefList_storage.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_storage.h
init/StaticPrefList_svg.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_svg.h
init/StaticPrefList_telemetry.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_telemetry.h
init/StaticPrefList_test.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_test.h
init/StaticPrefList_threads.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_threads.h
init/StaticPrefList_toolkit.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_toolkit.h
init/StaticPrefList_ui.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_ui.h
init/StaticPrefList_urlclassifier.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_urlclassifier.h
init/StaticPrefList_view_source.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_view_source.h
init/StaticPrefList_webgl.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_webgl.h
init/StaticPrefList_widget.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_widget.h
init/StaticPrefList_xul.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_xul.h
init/StaticPrefList_zoom.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefList_zoom.h
StaticPrefs_accessibility.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_accessibility.h
StaticPrefs_alerts.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_alerts.h
StaticPrefs_apz.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_apz.h
StaticPrefs_beacon.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_beacon.h
StaticPrefs_bidi.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_bidi.h
StaticPrefs_browser.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_browser.h
StaticPrefs_canvas.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_canvas.h
StaticPrefs_channelclassifier.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_channelclassifier.h
StaticPrefs_clipboard.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_clipboard.h
StaticPrefs_content.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_content.h
StaticPrefs_converter.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_converter.h
StaticPrefs_datareporting.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_datareporting.h
StaticPrefs_device.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_device.h
StaticPrefs_devtools.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_devtools.h
StaticPrefs_docshell.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_docshell.h
StaticPrefs_dom.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_dom.h
StaticPrefs_editor.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_editor.h
StaticPrefs_extensions.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_extensions.h
StaticPrefs_findbar.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_findbar.h
StaticPrefs_fission.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_fission.h
StaticPrefs_font.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_font.h
StaticPrefs_full_screen_api.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_full_screen_api.h
StaticPrefs_general.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_general.h
StaticPrefs_geo.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_geo.h
StaticPrefs_gfx.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_gfx.h
StaticPrefs_gl.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_gl.h
StaticPrefs_html5.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_html5.h
StaticPrefs_idle_period.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_idle_period.h
StaticPrefs_image.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_image.h
StaticPrefs_intl.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_intl.h
StaticPrefs_javascript.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_javascript.h
StaticPrefs_layers.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_layers.h
StaticPrefs_layout.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_layout.h
StaticPrefs_mathml.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_mathml.h
StaticPrefs_media.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_media.h
StaticPrefs_mousewheel.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_mousewheel.h
StaticPrefs_network.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_network.h
StaticPrefs_nglayout.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_nglayout.h
StaticPrefs_page_load.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_page_load.h
StaticPrefs_permissions.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_permissions.h
StaticPrefs_plain_text.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_plain_text.h
StaticPrefs_plugin.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_plugin.h
StaticPrefs_plugins.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_plugins.h
StaticPrefs_preferences.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_preferences.h
StaticPrefs_print.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_print.h
StaticPrefs_privacy.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_privacy.h
StaticPrefs_prompts.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_prompts.h
StaticPrefs_security.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_security.h
StaticPrefs_slider.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_slider.h
StaticPrefs_storage.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_storage.h
StaticPrefs_svg.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_svg.h
StaticPrefs_telemetry.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_telemetry.h
StaticPrefs_test.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_test.h
StaticPrefs_threads.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_threads.h
StaticPrefs_toolkit.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_toolkit.h
StaticPrefs_ui.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_ui.h
StaticPrefs_urlclassifier.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_urlclassifier.h
StaticPrefs_view_source.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_view_source.h
StaticPrefs_webgl.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_webgl.h
StaticPrefs_widget.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_widget.h
StaticPrefs_xul.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_xul.h
StaticPrefs_zoom.h: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += StaticPrefs_zoom.h
init/StaticPrefsCGetters.cpp: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += init/StaticPrefsCGetters.cpp
static_prefs.rs: init/$(MDDEPDIR)/StaticPrefListAll.h.stub ;
GARBAGE += static_prefs.rs
GARBAGE += init/$(MDDEPDIR)/StaticPrefListAll.h.stub
EXTRA_MDDEPEND_FILES += init/$(MDDEPDIR)/StaticPrefListAll.h.pp
init/$(MDDEPDIR)/StaticPrefListAll.h.stub: /home/kieran/Documents/browser/modules/libpref/init/generate_static_pref_list.py $(srcdir)/init/StaticPrefList.yaml
	$(REPORT_BUILD)
	$(call py_action,file_generate,/home/kieran/Documents/browser/modules/libpref/init/generate_static_pref_list.py emit_code init/StaticPrefListAll.h init/$(MDDEPDIR)/StaticPrefListAll.h.pp init/$(MDDEPDIR)/StaticPrefListAll.h.stub $(srcdir)/init/StaticPrefList.yaml)
	@$(TOUCH) $@

LOCAL_INCLUDES += -I$(topobjdir)/ipc/ipdl/_ipdlheaders
LOCAL_INCLUDES += -I$(topsrcdir)/ipc/chromium/src
LOCAL_INCLUDES += -I$(topsrcdir)/ipc/glue
COMPUTED_LDFLAGS += -Wl,-rpath-link,/home/kieran/Documents/browser/obj-x86_64-pc-linux-gnu/dist/bin -Wl,-rpath-link,/usr/local/lib
NONRECURSIVE_TARGETS += export
NONRECURSIVE_TARGETS_export += xpidl
NONRECURSIVE_TARGETS_export_xpidl_DIRECTORY = $(DEPTH)/xpcom/xpidl
NONRECURSIVE_TARGETS_export_xpidl_TARGETS += export
