# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

DEFINES += -DNDEBUG=1 -DTRIMMED=1 -DTELEMETRY_PING_FORMAT_VERSION=4 -DMENUBAR_CAN_AUTOHIDE=1 -DHAVE_SHELL_SERVICE=1 -DANDROID_PACKAGE_NAME=org.mozilla.firefox -DMOZ_APP_NAME=firefox -DMOZ_APP_BASENAME=Firefox -DMOZ_APP_VERSION=80.0 -DMOZ_APP_VERSION_DISPLAY=80.0 -DMOZ_BING_API_CLIENTID=no-bing-api-clientid -DMOZ_BING_API_KEY=no-bing-api-key -DMOZ_GOOGLE_LOCATION_SERVICE_API_KEY=no-google-location-service-api-key -DMOZ_GOOGLE_SAFEBROWSING_API_KEY=no-google-safebrowsing-api-key '-DMOZ_MACBUNDLE_NAME=Dot Browser.app' -DMOZ_MOZILLA_API_KEY=no-mozilla-api-key -DMOZ_WIDGET_TOOLKIT=gtk -DDLL_PREFIX=lib -DDLL_SUFFIX=.so -DDEBUG_JS_MODULES= -DOMNIJAR_NAME=omni.ja -DMOZ_UPDATER -DTOPOBJDIR=/home/kieran/Documents/browser/obj-x86_64-pc-linux-gnu
DIRS := subprocess
NONRECURSIVE_TARGETS += export
NONRECURSIVE_TARGETS_export += xpidl
NONRECURSIVE_TARGETS_export_xpidl_DIRECTORY = $(DEPTH)/xpcom/xpidl
NONRECURSIVE_TARGETS_export_xpidl_TARGETS += export
