# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

DEFINES += -DNDEBUG=1 -DTRIMMED=1 -DOS_POSIX=1 -DOS_LINUX=1 -DHAVE_STRDUP -DNR_SOCKET_IS_VOID_PTR -DSCTP_DEBUG -DLINUX -D__Userspace_os_Linux=1
LOCAL_INCLUDES += -I$(topobjdir)/ipc/ipdl/_ipdlheaders
LOCAL_INCLUDES += -I$(topsrcdir)/ipc/chromium/src
LOCAL_INCLUDES += -I$(topsrcdir)/ipc/glue
LOCAL_INCLUDES += -I$(topsrcdir)/media/mtransport/third_party/nrappkit/src/port/linux/include
LOCAL_INCLUDES += -I$(topsrcdir)/media/mtransport
LOCAL_INCLUDES += -I$(topsrcdir)/media/mtransport/third_party
LOCAL_INCLUDES += -I$(topsrcdir)/media/mtransport/third_party/nICEr/src/crypto
LOCAL_INCLUDES += -I$(topsrcdir)/media/mtransport/third_party/nICEr/src/ice
LOCAL_INCLUDES += -I$(topsrcdir)/media/mtransport/third_party/nICEr/src/net
LOCAL_INCLUDES += -I$(topsrcdir)/media/mtransport/third_party/nICEr/src/stun
LOCAL_INCLUDES += -I$(topsrcdir)/media/mtransport/third_party/nICEr/src/util
LOCAL_INCLUDES += -I$(topsrcdir)/media/mtransport/third_party/nrappkit/src/event
LOCAL_INCLUDES += -I$(topsrcdir)/media/mtransport/third_party/nrappkit/src/log
LOCAL_INCLUDES += -I$(topsrcdir)/media/mtransport/third_party/nrappkit/src/plugin
LOCAL_INCLUDES += -I$(topsrcdir)/media/mtransport/third_party/nrappkit/src/port/generic/include
LOCAL_INCLUDES += -I$(topsrcdir)/media/mtransport/third_party/nrappkit/src/registry
LOCAL_INCLUDES += -I$(topsrcdir)/media/mtransport/third_party/nrappkit/src/share
LOCAL_INCLUDES += -I$(topsrcdir)/media/mtransport/third_party/nrappkit/src/stats
LOCAL_INCLUDES += -I$(topsrcdir)/media/mtransport/third_party/nrappkit/src/util
LOCAL_INCLUDES += -I$(topsrcdir)/media/mtransport/third_party/nrappkit/src/util/libekr
LOCAL_INCLUDES += -I$(topsrcdir)/netwerk/sctp/src
LOCAL_INCLUDES += -I$(topsrcdir)/xpcom/tests
CPPSRCS += $(srcdir)/TestSyncRunnable.cpp
CPPSRCS += $(srcdir)/buffered_stun_socket_unittest.cpp
CPPSRCS += $(srcdir)/ice_unittest.cpp
CPPSRCS += $(srcdir)/multi_tcp_socket_unittest.cpp
CPPSRCS += $(srcdir)/nrappkit_unittest.cpp
CPPSRCS += $(srcdir)/proxy_tunnel_socket_unittest.cpp
CPPSRCS += $(srcdir)/rlogconnector_unittest.cpp
CPPSRCS += $(srcdir)/runnable_utils_unittest.cpp
CPPSRCS += $(srcdir)/sctp_unittest.cpp
CPPSRCS += $(srcdir)/simpletokenbucket_unittest.cpp
CPPSRCS += $(srcdir)/sockettransportservice_unittest.cpp
CPPSRCS += $(srcdir)/stunserver.cpp
CPPSRCS += $(srcdir)/test_nr_socket_ice_unittest.cpp
CPPSRCS += $(srcdir)/test_nr_socket_unittest.cpp
CPPSRCS += $(srcdir)/transport_unittests.cpp
CPPSRCS += $(srcdir)/turn_unittest.cpp
CPPSRCS += $(srcdir)/webrtcproxychannel_unittest.cpp
COMPUTED_LDFLAGS += -Wl,-rpath-link,/home/kieran/Documents/browser/obj-x86_64-pc-linux-gnu/dist/bin -Wl,-rpath-link,/usr/local/lib
