export const defaultSettings = {
    trackingProtection: 'strict',
    clearBrowsingOnExit: false,
    doNotTrack: true,
    anonymiseFingerprint: true,
    theme: 'light',
    customTheme: 'unset',
    pageZoom: 100,
    showHomeButton: false,
    showBookmarksBar: true,
    fontSize: "m",
    suggestionsFromKeywords: true,
    engine: 'duckduckgo',
    customEngine: 'unset',
    masterPasswordHint: '',
    location: 'defaultDownloadsFolder',
    askWhereToSave: false,
    language: 'en-US',
    spellCheck: true,
    highContrastMode: false,
    hardwareAcceleration: true
}