export const defaultSettings = [
    { key: 'trackingProtection', value: 'strict' },
    { key: 'clearBrowsingOnExit', value: false },
    { key: 'doNotTrack', value: true },
    { key: 'anonymiseFingerprint', value: true },
    { key: 'theme', value: 'light' },
    { key: 'pageZoom', value: 100 },
    { key: 'showHomeButton', value: false },
    { key: 'showBookmarksBar', value: true },
    { key: 'fontSize', value: 'm' },
    { key: 'suggestionsFromKeywords', value: true },
    { key: 'engine', value: 'duckduckgo' },
    { key: 'customEngine', value: 'unset' },
    { key: 'masterPasswordHint', value: '' },
    { key: 'location', value: 'defaultDownloadsFolder' },
    { key: 'askWhereToSave', value: false },
    { key: 'language', value: 'en-US' },
    { key: 'spellCheck', value: true },
    { key: 'highContrastMode', value: false },
    { key: 'hardwareAcceleration', value: true }
]